version: "3.1"
services:
  mongo:
    image: mongo:4.4.26-focal
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - avis-test

  mongo-express:
    image: mongo-express:1-18-alpine3.18
    restart: always
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
    networks:
      - avis-test

networks:
  avis-test: 
    external: true
    name: avis-test


  